version: "3.9"
services:
        maven:
                image: 'endika98/contarpalabras'
                #build: .
                #stdin_open: true # docker run -i
                #tty: true        # docker run -t
                volumes:
                        - miVol:/tmp 
        aplicacion:
                image: 'ubuntu'
                #depends_on:
                        #- 'maven'
                command: /bin/bash -c "/tmp/script.sh"
                volumes:
                        - miVol:/tmp
volumes:
        miVol :
                external: false
                name: 'miVol'
